driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
- name: debian-9
# - name: centos-6
# - name: centos-7
# - name: fedora-27
# - name: ubuntu-14.04
# - name: ubuntu-16.04
# - name: opensuse-leap
# - name: amazonlinux
#   driver_config:
#     box: mvbcoding/awslinux

suites:
  - name: setup
    run_list:
      - recipe[test::setup]
      - recipe[test::single_port]

  - name: default
    run_list:
      - recipe[test::setup]
      - recipe[test::single_port]
      - recipe[test::twice_port]
      - recipe[test::range_port]
      - recipe[test::bad_port]
      - recipe[test::module]
      - recipe[test::module_directory]
      - recipe[test::fcontext]
      - recipe[test::fcontext_filetype]
      - recipe[test::single_port_add_to_range]
