---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[gd-test-helper]
      - recipe[selinux::default]
      - recipe[selinux_policy_test::default]
