# Use Travis's cointainer based infrastructure
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

branches:
  only:
    - master

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
